### ISSUE TITLE
Compatible with Hugo 0.91?

### ISSUE THREAD

**Issue by jfmartin67** [svendahlstrand/plugin-surprise-me#1]
After switching my MB website to Hugo 0.91, the plugin seems not to respond to the /surprises-me/ URL. Please, advise.

**Comment by svendahlstrand** [comment]
I know it's compatible with 0.91, but obviously, something is up. Maybe the version switch caused this? Let's try:

1. Remove the page *Surprise me!* for now. (But keep the plug-in installed.)
2. [Force a rebuild](https://micro.blog/account/logs) of your blog.

When the rebuild is done (watch the log), manually visit https://numericcitizen.micro.blog/surprise-me/.

Does that work?

**Comment by jfmartin67** [comment]
Found out that the missing "/" at the end of the URL in the page definition... was ok with previous Hugo version, though. Added the final / and it works fine!
